question_data = [
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "Clefairy was intended to be Ash's starting Pokemon in the pilot episode of the cartoon.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "Studio Ghibli is a Japanese animation studio responsible for the films 'Wolf Children' and 'The Boy and the Beast'.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
         "question": "The anime Attack on Titan was directed by Tetsurō Araki, the same person who directed the anime Highschool of the Dead.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "In Pokemon, Ash's Pikachu refuses to go into a pokeball.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "Throughout the entirety of 'Dragon Ball Z', Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "Kiznaiver is an adaptation of a manga.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "Druid is a mage class in 'Log Horizon'.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "In the 'To Love-Ru' series, Golden Darkness is sent to kill Lala Deviluke.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
         "question": "In 'To Love-Ru: Darkness', Yami reveals her real name is Eve.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "In the 'To Love-Ru' series, Peke is considered a female robot.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
         "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
         "question": "In Full Metal Panic!, Whispered are those who are capable of creating Black Technology.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "The protagonist in 'Humanity Has Declined' has no discernable name and is simply referred to as 'I' for most of the series.",
         "correct_answer": "True", "incorrect_answers": ["False"]}

]
